tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: dbt
      schema: dev
      warehouse: COMPUTE_WH